# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Manish Yadav
title: DevOps Engineer | Site Reliability Engineer (SRE)
email: manishyadav996@gmail.com
phone: +91-9899990024
linkedin_username: manishyadav92

# Dark Mode (true/false/never)
darkmode: false

# Additional icon links
additional_links:
- title: LinkedIn
  icon: fab fa-linkedin
  url: https://www.linkedin.com/in/manishyadav92

# About Section
about_content: |
  With 9.7 years of experience working as a DevOps Engineer and Site Reliability Engineer (SRE), with a Bachelor's degree in Computer Science. I have a deep understanding of infra-as-code principles, DevOps tools, and open-source technologies. I have effectively used this knowledge to help design system capacity, automate and support IT infrastructure and application deployment processes, resulting in enhanced production services and high availability and scalability.

content:
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Amazon Development Centre
        sub_title: DevOps Engineer
        caption: June 2021 – Nov 2022
        description: |
          Currently, I am responsible for creating and maintaining distributed, serverless, and scalable infrastructure for Amazon retail Website and Amazon payment gateway, leveraging Amazon Web Technologies' (AWS) containerization services (ECS, EKS, Fargate).

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Maharishi Dayanand University
        sub_title: Bachelor of Technology (Computer Science)
        caption: 2008-2012

  - title: Certifications
    layout: list
    content:
      - layout: left
        title: RedHat Certified Engineer (120-102-249)
      - layout: right
        title: AWS Solution Architect – Associate

  - title: Tools and Technologies
    layout: list
    content:
      - layout: left
        title: DevOps Tools
        description: AWS DevOps, GIT
      - layout: right
        title: Programming/Scripting
        description: Bash/Shell scripting, Python
      - layout: left
        title: Container Technologies
        description: Docker, Kubernetes
      - layout: right
        title: Serverless
        description: AWS Lambda, Fargate, API Gateway, Step Functions, Amazon EventBridge
      - layout: left
        title: Configuration Management
        description: Terraform, Ansible, AWS CloudFormation
      - layout: right
        title: Other DevOps Tools
        description: Git/GitHub, Prometheus, Splunk, Spinnaker, CircleCI
      - layout: left
        title: Documentation Tools
        description: Docusaurus, Jekyll

  - title: Recent Project Experience
    layout: list
    content:
      - layout: left
        title: Multi-Region Cloud Architecture
        description: |
          Created a multi-region, highly available cloud architecture using Terraform, including disaster recovery.

      - layout: right
        title: Microservices-based Architecture
        description: |
          Developed reusable Terraform modules for deploying a microservices-based architectureon AWS.

      - layout: left
        title: Infrastructure Deployment
        description: |
          Administered and deployed infrastructure across multiple cloud providers, using Terraform Cloud for centralized remote state management and collaboration for scalability and maintainability.

      - layout: right
        title: Hybrid Cloud Infrastructure
        description: |
          Designed and implemented a hybrid cloud infrastructure that combined on-premises resources such as VPN connections, load balancers, and databases with cloud-based resources.

      - layout: left
        title: Blue-Green and Canary Deployments
        description: |
          Implemented blue-green and canary deployments for versioned applications with near-zero downtime.

      - layout: right
        title: Multi-Tier Web Server Infrastructure
        description: |
          Built a multi-tier web server infrastructure for a streaming platform.

      - layout: left
        title: AWS App2Container Workflow Automation
        description: |
          Automated AWS App2Container workflow using AWS SDK, Ansible, and Rundeck.

      - layout: right
        title: Amazon EKS Deployment
        description: |
          Fully automated Amazon EKS deployment with Ansible and Circle CI.

      - layout: left
        title: AWS Lambda REST API
        description: |
          Built REST APIs with AWS Lambda and integrated with ECS/EKS.

      - layout: right
        title: Service Now Integration
        description: |
          Wrote and built Service Now integration with AWS tools/Scripts using Python.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
